name: 🫣 Android CI

on:
  push:
    branches: [ "main", "custom-rethink-release" ]
  pull_request:
    branches: [ "main", "custom-rethink-release" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Locked to Website Full for full 64-bit Samsung S23 (arm64-v8a) compatibility
      VARIANT: assembleWebsiteFullRelease
    steps:
    - name: 🥏 Checkout
      uses: actions/checkout@v4
          
    - name: ☕️ JDKv17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
            
    - name: ⚡️ +x gradlew
      run: chmod +x gradlew
          
    - name: 🎪 Secrets
      if: success()
      run: |
        mkdir -p app/src/debug
        echo "${GSCV_TEST_JSON}" > app/src/debug/google-services.json
        wc -lwm app/src/debug/google-services.json
      env:
        GSCV_TEST_JSON: ${{ secrets.GOOGLE_SERVICES_TEST_JSON }}
            
    - name: 🚂 Assemble Release
      if: success()
      run: |
        ./gradlew lint
        ./gradlew \
          ${VARIANT} \
          --info \
          --warning-mode all
      env:
        VARIANT: ${{ env.VARIANT }}

    - name: 📥 Install Legacy Build Tools
      if: success()
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;29.0.3"
            
    - name: 🔐 Sign Release APK
      id: sign_app
      uses: r0adkll/sign-android-release@v1
      with:
        # Corrected path for the Website build variant
        releaseDirectory: app/build/outputs/apk/websiteFull/release
        signingKeyBase64: ${{ secrets.SIGN_KEY_BASE64 }}
        alias: ${{ secrets.SIGN_ALIAS }}
        keyStorePassword: ${{ secrets.SIGN_STORE_PASS }}
        keyPassword: ${{ secrets.SIGN_KEY_PASS }}
            
    - name: 📦 Upload Signed APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: rethink-signed-release-apk
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
